AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "lib/generators/**/templates/**/*"
  NewCops: disable

Style/Documentation:
  Enabled: true
  Exclude:
    - "lib/generators/action_sentinel_group/**"
    - "spec/support/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "spec/**/*"
    - "action_sentinel_group.gemspec"

Naming/HeredocDelimiterNaming:
  Enabled: true
  Exclude:
    - "action_sentinel_group.gemspec"
